[package]
name = "cshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
hex = "0.4.3"
hex-literal = "0.4.1"
sha3 = "0.10.8"
